set StdArithNoWarnings 1
set NumericStdNoWarnings 1

proc get_generics {dut_name} {
    set path [find instances -bydu $dut_name -nodu]
    echo "Extracting generics or parameters from $path ($dut_name) to be used by other tools into generics.txt"
    env $path
    set X [Show]


    set genericfile [open ./generics.txt w]
    radix -unsigned
#    puts $genericfile "# autogenerated generic file for $path"
    # Find Generics
    set Y [lindex $X 2]
    set indexlist_p [lsearch -all $Y "*Parameter*"]
    set indexlist_g [lsearch -all $Y "*Generic*"]
    
    foreach i $indexlist_p {
	set G [lindex $Y $i]
	set g [lindex [split $G] 1]
	set val [examine $g]
	puts -nonewline $genericfile "-G $dut_name/$g=$val "
    }
    foreach i $indexlist_g {
	set G [lindex $Y $i]
	set g [lindex [split $G] 1]
	set val [examine $g]
	puts -nonewline $genericfile "-G $dut_name/$g=$val "
    }


#echo "Found following:$Y"
puts $genericfile ""
close $genericfile
echo "Done"
}

get_generics $1
exit -f
