#
#----------------------------------------------------------------------
#   Copyright 2009-2012 Mentor Graphics Corporation
#   All Rights Reserved Worldwide
#
#   Licensed under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in
#   compliance with the License.  You may obtain a copy of
#   the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in
#   writing, software distributed under the License is
#   distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
#   CONDITIONS OF ANY KIND, either express or implied.  See
#   the License for the specific language governing
#   permissions and limitations under the License.
#----------------------------------------------------------------------

# This Makefile adds support for an OSCI SystemC version of UVM-Connect SC for
# uses with a non-Questa OSCI SystemC kernel. See comments in
# Makefile.uvmc_sysc_standalone for more details.

all: build clean

include common.mk

LIB = ../lib
LIBOBJ = $(LIB)/$(XL_BUILD_PLATFORM)/osci

INCL += \
    -I$(SYSTEMC)/include -I$(SYSTEMC_TLM_HOME) \
    -I$(MTI_HOME)/include -I$(UVM_HOME)/src/dpi

build:
	$(MAKE) -f Makefile.uvmc_sysc_standalone build \
		LIBOBJ="$(LIBOBJ)" INCL="$(INCL)"

clean:
	$(MAKE) -f Makefile.uvmc_sysc_standalone clean \
		LIBOBJ="$(LIBOBJ)" INCL="$(INCL)"

cleanall:
	$(MAKE) -f Makefile.uvmc_sysc_standalone cleanall \
		LIBOBJ="$(LIBOBJ)" INCL="$(INCL)"
